# -*- coding: utf-8 -*-
"""dese2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XE3ExmEdBgoji_zaWrdYfBleiXGqhQGc
"""

if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
BiocManager::install("DESeq2")

library(DESeq2)

input_file <- "GSE197265_H9_TPRX2_ctrl_vs_OE_rep123_count.txt"
count_data <- read.table(input_file, header=TRUE, sep="\t", row.names=1)

col_data <- data.frame(
  condition = factor(c(rep("Control", 3), rep("Treatment", 3)))
)

dds <- DESeqDataSetFromMatrix(countData = count_data, colData = col_data, design = ~condition)

dds <- DESeq(dds)
res <- results(dds)

write.csv(as.data.frame(res), "deseq2_results.csv")